// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace TargetedHomes.Models;

public partial class TargetHomeContext : DbContext
{
    private readonly IConfiguration _config;
    public TargetHomeContext(IConfiguration config)
    {
        _config = config;
    }

    public TargetHomeContext(DbContextOptions<TargetHomeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<poi_groups> poi_groups { get; set; }

    public virtual DbSet<poi_locs> poi_locs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseNpgsql(_config["TargetHomeDatabase"]);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<poi_groups>(entity =>
        {
            entity.HasKey(e => e.group_id).HasName("poi_groups_pkey");

            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<poi_locs>(entity =>
        {
            entity.HasKey(e => e.loc_id).HasName("poi_locs_pkey");

            entity.Property(e => e.address)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.city)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.state)
                .IsRequired()
                .HasMaxLength(2)
                .IsFixedLength();
            entity.Property(e => e.zip)
                .IsRequired()
                .HasMaxLength(5)
                .IsFixedLength();

            entity.HasOne(d => d.group).WithMany(p => p.poi_locs)
                .HasForeignKey(d => d.group_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("poi_locs_poi_group_id_fkey");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}